# Generated by Django 5.2 on 2025-05-05 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drinks.category'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
