# Generated by Django 5.2 on 2025-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
