# Generated by Django 5.2 on 2025-05-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_drink_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='description',
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drinks/'),
        ),
    ]
