# Generated by Django 5.2 on 2025-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='share_profile',
            field=models.BooleanField(default=True, help_text='Allow bartenders to view your profile (e.g., favorite drinks, visit frequency).'),
        ),
    ]
